services:
  app:
    build:
      context: .
    ports:
      - "8080:80"
    environment:
      - PYTHONPATH=/opt/app
    depends_on:
      - prometheus
      - grafana
    networks:
      - monitoring_net

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring_net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring_net

volumes:
  grafana-data:

networks:
  monitoring_net:
