name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-tag:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Obter a Última Tag
      - name: Get Latest Tag
        id: get_latest_tag
        run: |
          # Obtém a última tag no repositório
          latest_tag=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      # 3. Incrementar a Versão
      - name: Calculate New Tag
        id: calculate_new_tag
        run: |
          # Incrementa a versão da tag
          IFS='.' read -r major minor patch <<<"${latest_tag#v}"
          patch=$((patch + 1))
          new_tag="v$major.$minor.$patch"
          echo "new_tag=$new_tag" >> $GITHUB_ENV

      # 4. Criar e Publicar a Nova Tag
      - name: Create New Tag
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ env.new_tag }}
          git push origin ${{ env.new_tag }}

      # 5. Configurar Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 6. Build da Imagem Docker com a Nova Tag
      - name: Build Docker Image
        run: |
          docker build -t irvids/irvi-passenger-python:${{ env.new_tag }} .

      # 7. Testar a Imagem Docker
      - name: Test Docker Image
        run: |
          docker run --rm -e PYTHONPATH=/opt/app irvids/irvi-passenger-python:${{ env.new_tag }} pytest app/tests/

      # 8. Login no Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 9. Push da Imagem para o Docker Hub com a Nova Tag
      - name: Push Docker Image
        run: |
          docker push irvids/irvi-passenger-python:${{ env.new_tag }}
