name: CI/CD Pipeline

on:
  push:
    tags:
      - 'v*' # Aciona a pipeline ao criar uma tag com o formato "v1.0.1"
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Configuração do Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Build da imagem Docker com a tag da versão
      - name: Build Docker Image
        run: |
          docker build -t irvids/irvi-passenger-python:${{ github.ref_name }} .

      # 4. Testar a Imagem Docker
      - name: Test Docker Image
        run: |
          docker run --rm -e PYTHONPATH=/opt/app irvids/irvi-passenger-python:${{ github.ref_name }} pytest app/tests/

      # 5. Login no Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6. Push da imagem para o Docker Hub com a tag da versão
      - name: Push Docker Image
        run: |
          docker push irvids/irvi-passenger-python:${{ github.ref_name }}
