name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Configuração do Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Build da imagem Docker
      - name: Build Docker Image
        run: |
          docker build -t irvi-passenger-python:${{ github.sha }} .

      # 4. Testar a Imagem Docker
      - name: Test Docker Image
        run: |
          docker run --rm -e PYTHONPATH=/opt/app irvi-passenger-python:${{ github.sha }} pytest app/tests/

      # 5. Login no Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6. Tag da imagem para o Docker Hub
      - name: Tag Docker Image
        run: |
          docker tag irvi-passenger-python:${{ github.sha }} irvids/irvi-passenger-python:latest

      # 7. Push da imagem para o Docker Hub
      - name: Push Docker Image
        run: |
          docker push irvids/irvi-passenger-python:latest
